sudo: required
services:
  - docker
before_install:
  - docker build -t pciaco/pietrowebapp:latest .
script:
  - docker images pciaco/pietrowebapp
after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pciaco/pietrowebapp