sudo: required
services:
  - docker
before_install:
  - docker build -t pciaco/pietrowebapp:latest .
script:
  - docker images pciaco/pietrowebapp
deploy:
  provider: script
  script: bash docker_push